### ISSUE TITLE
Words are being broken on steemgigs card

### ISSUE THREAD

**Issue by tobias-g1** [steemgigs/steemgigs#111]
![image](https://user-images.githubusercontent.com/17148879/54092268-29f14d00-4382-11e9-8121-a7ff4d7cf1ff.png)

**Comment by cadawg** [comment]
I just had a look at the site, and noticed this in the properties
![image](https://user-images.githubusercontent.com/28988626/54184854-87c78700-449f-11e9-9b21-7613d91b7239.png)
I don't know, but that seems to be an invalid value, I feel like maybe changing it to

```
word-wrap: break-word;
```

may fix the issue but my browser isn't wanting to let me play ball.
