### ISSUE TITLE
Pending: Add A Basic Display Page On SteemGigs.org Called BroPro

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#117]
We want to build a basic page that will display a few 'certified users' for a start, who will accept the teardrops tokens for their minutes.

For now we call it basic because entries to the page will be done manually, not via an admin panel etc

**Comment by tobias-g1** [comment]
Can you provide a list of users you would like to have on this please?

**Comment by surpassinggoogle** [comment]
for now, we can start with you and me. I will get a few others but it wont be many for now

**Comment by surpassinggoogle** [comment]
On more account name is @ankarlie, i will get the full details later today

**Comment by tobias-g1** [comment]
Resolved in #136
