### ISSUE TITLE
Proposed Draft of A Privacy Policy for SteemGigs 

### ISSUE THREAD

**Issue by Pope19** [steemgigs/steemgigs#12]
Greetings,

I noticed that SteemGigs do not have a privacy policy and i decided to create a privacy policy for SteemGigs in light .

Privacy policy is a very important document on any website that  details a company's views on information collected from visitors and how  it intends to secure that information. It also helps to instill more  confidence in the prospective site visitors/users and give users an idea of  what to expect and what not to expect on the site.
 
Here is the proposed privacy policy i drafted for SteemGigs.org. 

[Proposed privacy policy for SteemGigs](https://www.dropbox.com/s/h0aw7idzqcapplg/SteemGigs%20PRIVACY%20POLICY.docx?dl=0). 

Please take a look at it for your own personal consideration. All constructive criticism and suggestions are welcomed.

**Comment by jalasem** [comment]
thanks so much for the contribution @Pope19 We found this useful and applicable to our use case

**Comment by tobias-g1** [comment]
Would you like to include this in the site @surpassinggoogle

**Comment by tobias-g1** [comment]
@surpassinggoogle Seems a shame to waste this if we planned to implement this previously, this would be a quick task to add in? Probs about 20 minutes. Would you like to include it?
