### ISSUE TITLE
Issue with Search (Possible unimplemented feature)

### ISSUE THREAD

**Issue by tobias-g1** [steemgigs/steemgigs#13]
Please close if this isn't useful, but saw a task to improve search and thought you might like to see my current behavior. I know that you don't want bug reports (this is possible and likely and unimplemented feature) at the moment so apologies if this is an annoyance!

#### Expected behavior
When I have opened the search pop up I should have the ability to search by pressing return and escaping the pop up using the ESC key.

#### Actual behavior
After launching the search pop up. When I enter my search term and press return nothing happens, no search results are shown. Upon pressing the Esc key when the search popup is open the popup does not close. 

#### How to reproduce

1. Visit [SteemGigs.org](https://steemgigs.org)
2. When signed in to the application click on the search icon located within the top navigation bar.
3. This will bring up a pop up a search pop up. 
4.  Enter a search term and press return, nothing will happen.
4. press ESC on your keyboard, the search popup will not close. 

Please note: I have included the Mac keyboard viewer within my image to help show by key presses. 

* Browser: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating system: MacOS HighSierra Version 10.13 (17A365)

#### Recording Of The Bug

Please use the image below to view the issue which I discuss:

https://res.cloudinary.com/hpiynhbhq/image/upload/v1521051542/hxx7u6x1w3mh4as7x9vv.gif

**Comment by jalasem** [comment]
Nice observation, it's being worked on, that is why you see it on the task board, but the observation and suggestion is warmly appreciated

**Comment by tobias-g1** [comment]
Resolved by #49
