### ISSUE TITLE
Minor Issue with CSS & Profile Routing

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#134]
- [x] Issue with routing to profile

 When you are on a user's profile and load up a steemgigs post url on the browser e.g https://steemgigs.org/steemgigs/@jackdogho/help-you-set-up-your-professional-e-commerce-store and you try to click on 'edit profile' tab while that post or user-profile is open, it doesn't load up the correct url that would lead to the 'edit profile' page.

Also small bug with the upvote button for replies:

- [x] Issue with upvoting

It is impossible to vote on a comment underneath a steemgigs post. It is possible to vote on the post itself but not on the comment. 

![image](https://user-images.githubusercontent.com/23729959/55287229-d4d0b600-53d8-11e9-86fb-6af8bccb011a.png)

**Edit:**
It is possible to vote but there is some alignment issues when it comes to the cursor. it has to be placed slightly above the upvote button before the 'hand cursor' displays.

- [x] Issue with tags
**Slight Enhancement Needed**:
![steemgigs bugs 2](https://user-images.githubusercontent.com/23729959/55287488-04cd8880-53dc-11e9-8256-b2522683065b.png)

- [x] Issue with expertise copy

![steemgigs bugs](https://user-images.githubusercontent.com/23729959/55287489-05661f00-53dc-11e9-961c-60e5472cdc01.png)

**Comment by tobias-g1** [comment]
Resolved in #136
