### ISSUE TITLE
Slight Edit To Current Steemgigs.org On Mobile.

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#135]
Please add appropriate icons for the '+' that allows users choose appropriate editors. The current '+' button leads to a series of unrelated icon that gives no hint related to the path (post editors)

![](https://cdn.discordapp.com/attachments/403705949761830922/561848166954303498/Screenshot_2019-03-31-17-43-50.png)

**Comment by tobias-g1** [comment]
See if you like the change I made in this release to see if it works for you

**Comment by surpassinggoogle** [comment]
Yes bro, i will close this for now. We will focus on enhancing mobile overtime. Thank you alot for the addition
