### ISSUE TITLE
Proposed SteemGigs help center for buyers (2)

### ISSUE THREAD

**Issue by edikanefanga** [steemgigs/steemgigs#14]
This is the continuation of the Help Center I proposed. As stated earlier in the first part, there are Help Topics under the Help Center and I am explaining each of them in details including their sub topics. Also in this part of the Help Center which deals with communication, i included My Contact button and My Favorite option which the inclusion of the former and latter on the SteemGigs website were earlier suggested by me (@edikanefanga) in utopian.io with stated reasons and advantages.

The inclusion of a help center for buyers will help in the speedy navigation of the SteemGigs website by buyers and also help in answering pending questions on the minds of buyers.

Here is the link to the help center (2)
[Link](https://www.dropbox.com/s/kk1jyvrlxvfcyt2/Help%20Center%20%282%29.doc?dl=0)

I am open to a wide range of suggestions and constructive criticism

**Comment by jalasem** [comment]
great, will look into this, thank you

**Comment by tobias-g1** [comment]
Only using https://github.com/steemgigs/steemgigs/issues/7
