### ISSUE TITLE
Creating A Compelling About Us Page Content For SteemGigs.com

### ISSUE THREAD

**Issue by order4adwriter** [steemgigs/steemgigs#15]
SteemGigs , a website created to promote hardwork, ingenuity and individual brilliance among Steemians globally. needs a befitting About Us Page.

Every site needs a designated About Us Page to tell its prospective clients and visitors  what that particular website is all about, what the goals for the creation of the site are, and what the website stands for and how it intends to  help the site visitors achieve their own goals.

Due to the nature of its objectives and  somewhat uniqueness of its operations, having a well written About Us page will assist new visitors of the site  to get a quick, positive  first impression of  Steemgigs.com, and its services.

 It will also be an ideal tool which such visitors can use  via a link to spread the word about SteemGigs .com

In terms of SEO,  SERP and organic visitors ,writing certain keywords on strategic places of an About Us web page copy aids search engine spiders/bots to gather info about a site, thus placing the links of the site as close to the top  of the search results as possible, and  easily retrievable whenever  they are searched on search engines.

I would therefore like to write compelling but befitting web page copy for the SteemGigs.com About Us Page.

I hope my proposal is accepted as soon as possible as I look forward to contributing my copywriting skills and abilities to the development and success of the SteemGigs.com project.

**Comment by jalasem** [comment]
Thank you so much, before getting started, I will like you to read these and understand them

- https://github.com/steemgigs/steemgigs/blob/master/ABOUT.md
- https://steemit.com/steemgigs/@surpassinggoogle/the-grand-picture-the-detailed-faq-s-for-https-steemgigs-org-and-all-the-answers-please-bookmark-this before getting started.
- Use google docs or Dropbox paper to write the write your content

Thank you once again for stopping by to contribute to this project 

@surpassinggoogle please make your comment for any observation or correction

**Comment by order4adwriter** [comment]
Thanks for your approval.

I have already read these posts... but will read them again during the course of writing the About Me content for SteemGigs.com

Working on it now.

**Comment by surpassinggoogle** [comment]
Thank you alot @order4adwriter for your intentions. Let's see how it goes. The links jalasem left you are essential to read, so that you can grasp the grand picture and the full scope of where we are headed and the url to steemgigs is steemgigs.org

**Comment by order4adwriter** [comment]
thanks for your encouraging  message @surpassinggoogle...wow I really envy your moniker...wish I thought of it first!

I read the posts and I admire you guys for trying to put the rest of us Steemian freelancers on the spotlight. Thanks for your effort.

Anyway, here is the About Us Page as written by me.

I believe its great ... but if you need me to make any changes, please let me know asap.

looking forward to your positive reply.

**Comment by order4adwriter** [comment]
https://www.dropbox.com/sh/6gahls3y06xq01m/AADAy5I1vMXY9Xo-hGAbp-e9a?dl=0

**Comment by order4adwriter** [comment]
I'm done with the about us page...still no reply from you guys.....

**Comment by jalasem** [comment]
Reviewed, check the comment on your pull request. Sorry for the delay
