### ISSUE TITLE
Enhance Navigation To Other Core Aspects Of Steemgigs And Other Post-Editors (Additional 20 steem bounty + 150 TEARDROPS)

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#153]
This is a simple enhancement to the look of our site to improve navigation to other to other key aspects of steemgigs.

For instance, we now want our homepage (upon sign-in) to look like this:

![steemgigs homepage new banner](https://user-images.githubusercontent.com/23729959/57611055-9ec04d80-75a4-11e9-961b-f0eb3d42e103.png)

> The banner is a collection of fading-out images linking to other aspects of steemgigs. Users would be able to click on the banners.

Then, kindly add a tabs namely 'BROPRO' & 'SurpassingGoogle' to the top-right area of our homepage (prior to sign-in) and some clickable items labelled underneath the search box as seen below:

![steemgigs search 4](https://user-images.githubusercontent.com/23729959/57788809-50f54200-776a-11e9-87e3-d01c641543ff.png)

Also, when users search and find no result, the resulting pages (signed-in/signed-out) should be something like this:
![steemgigs search 3](https://user-images.githubusercontent.com/23729959/57788955-96b20a80-776a-11e9-9c61-f703779dada1.png)

>  (this should apply across all categories and subcategories)

Where they find result, we want you to add a new item (text) to the resulting page as seen below (this should apply across all categories and subcategories):
![steemgigs search 2](https://user-images.githubusercontent.com/23729959/57789133-e2fd4a80-776a-11e9-841a-54d4b7c6cbdf.png)

> I will can provide the respective URL-paths for each new addition in a DM

**Comment by ali-h** [comment]
done
