### ISSUE TITLE
Label Non-Expert Gigs (Additional Bounty Of 15 steem + 150 TEARDROPS)

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#158]
This is a simple task to make a distinction between expert and non-expert gigs, so that clients know what kind of gig they are availing.

To accomplish this we will simply an a tiny badge to non-expert gig-cards as seen below:
![steemgigs search non-expert](https://user-images.githubusercontent.com/23729959/57790197-d843b500-776c-11e9-832b-ed4d6cbbc453.png)

non-expert gig-cards are all cards or posts emanating from or published under the main category labelled 'untalented-steemgigs' and its respective sub-categories.

**Comment by ali-h** [comment]
done
