### ISSUE TITLE
Request To run Promotion For Steemgigs

### ISSUE THREAD

**Issue by gutzygwin** [steemgigs/steemgigs#21]
I noticed your recent post on request for logo designs and guidelines mainly because I've been a true follower of your blog on steemit/steemgigs. I would like to contribute also to steemgigs but I'm not a logo designer but I have other ways i can contribute to steemgigs which i hope will be befitting to you. 
    I have a facebook page which I believe can be used to promote steemgigs with the use of a promotional ad will I will provide. 
    I want to request your permission before I can carry out the promotion or task. In doing this, I hope to contribute to the steemgigs community in my own way. 

Thank you.

**Comment by jalasem** [comment]
thank you it will be appreciated

**Comment by gutzygwin** [comment]
Thank you for accepting my request. I will do my best to publicizing steemgigs.
