### ISSUE TITLE
PROPOSED STEEMGIGS TERMS AND CONDITIONS

### ISSUE THREAD

**Issue by jeremiahokoh** [steemgigs/steemgigs#24]
Hello,

I am a big fan and user of the STEEMGIGS platform. For an awesome project like STEEMGIGS, it is very important that TERMS AND CONDITIONS for making use of STEEMGIGS, is created. So I took out some time to create the TERMS AND CONDITIONS.

[VIEW STEEMGIGS TERMS & CONDITIONS](https://www.dropbox.com/s/bubdpcgjri7smxv/STEEMGIGS%20T%26C.docx?dl=0)

You can check out the link above for the proposed draft. I am open to suggestions and constructive criticism. Any other person is allowed to update the document to ensure that STEEMGIGS has a standard TERMS AND CONDITIONS agreement for it's users always.

Thanks and I hope you like it.

**Comment by tobias-g1** [comment]
Link no longer accessible for terms and conditions.
