### ISSUE TITLE
Help Us Work On All Our Post-Cards (Thumbnails), So That They Are Open-able In New Tabs.

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#27]
We want to maximize the use of https://steemgigs.org, to where people are able to view multiple posts at once, simply by being able to expand post-cards or post-thumbnails in "new tabs".

### Current Behavior: 
Clicking on a post-card (thumbnail), will expand to "full post" on the same page. 
To pull up or expand another post-card, you will have to click on "back", to be led back to the catalog of post-cards, from where you can now click on another card, to view (expand). 
**See screenshot for reference:**
![steemgigs org new featttttttttttttttttt](https://user-images.githubusercontent.com/23729959/37878810-214d8a1e-30a1-11e8-9db4-d886639fd469.png)

### Expected Behavior:
Make it possible for post-cards (thumbnails) to open in "new tab", whenever a user right clicks on the post-card "title" to "open in new tab".

> Direct clicks on the post-card title are allowed to load on the same page.

**Comment by tobias-g1** [comment]
This has been resolved as per the above commits, tested and works as expected on live site.
