### ISSUE TITLE
Help Us Tweak Existing Permalinks For Every Post Created On https://steemgigs.org

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#28]
Each post on SteemGigs is created under a default first tag called **"steemgigs"**. 
We want this default first tag; "steemgigs" to appear as part of the permalink rule, for each post created using https://steemgigs.org
**

> e.g https://steemgigs.org/steemgigs/@profileusername/steemgigs-unique-post-identifier

**

### Current Behavior:
In general, the permalink for existing posts on SteemGigs, look like this:
**

> https://steemgigs.org/@amulla505/help-you-to-evacuate-google-penguinpanda-or-manual-punishment-and-to-achieve-top10

**
You will notice that permalink rule constitutes of the site domain name, followed by the **"SteemGigs profile username"**, omitting the first default tag; **"steemgigs"**

### Expected Behavior:
Permalink should now include the default first tag; **"steemgigs"**, just after the site domain name; https://steemgigs.org before the SteemGigs profile username, with all other things remaining the same. 
**i.e for instance, the URL we mentioned just earlier, should look like this:**

> https://steemgigs.org/steemgigs/@amulla505/help-you-to-evacuate-google-penguinpanda-or-manual-punishment-and-to-achieve-top10

**Comment by tobias-g1** [comment]
@surpassinggoogle What's the status if this issue, was this resolved?
