### ISSUE TITLE
Help Us Add A Simple "Video URL Embed" Reminder Feature To The "Portfolio" Segment Of The "Gig Create" Editor On https://steemgigs.org

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#29]
This is a simple addition that we would like you to add, to the [Gig Create Editor](https://steemgigs.org/create_gig) on https://steemgigs.org

### Current Behavior:
Just before the last phase of the editor, involving "Portfolio", there is **no option or reminder** to tell SteemGiggers to consider **attaching a video URL** of themselves, tell potential clients why they should avail of their Gigs. **Here is a mock-up shot of how it currently looks:**
![image](https://user-images.githubusercontent.com/23729959/37879344-1b19f8d6-30aa-11e8-9039-8655aa116807.png)

### Expected behavior:
Please look at the mock-up of the addition (feature), we would like you to add to that "Portfolio" segment of the [Gig Create Editor](https://steemgigs.org/create_gig):
![steemgigs org new feattttttttttttttttttt](https://user-images.githubusercontent.com/23729959/37879298-50f6cc3c-30a9-11e8-9620-09902264fddb.png)

> Note that the feature for **video URL embed** already exist across all editors on the site, thus, you can simple look to detach, replicate and attach. **See this:**

![image](https://user-images.githubusercontent.com/23729959/37879324-b40ff97e-30a9-11e8-9ae1-f034c66046a2.png)

**Comment by tobias-g1** [comment]
This has been resolved.
