### ISSUE TITLE
Request to run promotion for steemgigs 

### ISSUE THREAD

**Issue by engrbrain1** [steemgigs/steemgigs#31]
Steemgigs is one of my best platform and I follow it up on every day, So i would like to contribute also to syeemgigs in a way which i hope will be appropriate for you .
I have a facebook page which I believe can be used to promote steemgigs with the use of a promotional ad will I will provide.
I want to request your permission before I can carry out the promotion. In promoting steemgigs, I hope to contribute to the steemgigs community in my own way.

**Comment by jalasem** [comment]
Please tell us details about your page, so that we can check it out

**Comment by engrbrain1** [comment]
My page on facebook is an open source promotion page which I use in running
promotonal and on different open sources and steemgigs is one of the open
source am promoting, here is a link to the facebook page
https://www.facebook.com/engrbrain01/
Here is also the link to the promotional ad I started already
https://m.facebook.com/story.php?story_fbid=1791909611112635&id=1790805737889689


On 30 Mar 2018 16:24, "Abdul-Samii Ajala Olalekan" <notifications@github.com>
wrote:

Please tell us details about your page, so that we can check it out

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/steemgigs/steemgigs/issues/31#issuecomment-377548802>,
or mute the thread

**Comment by jalasem** [comment]
thanks a lot for the contribution.

**Comment by engrbrain1** [comment]
Thank you also for your time, so do I have your permission to continue the promotional ad on my facebook page

**Comment by jalasem** [comment]
Sure, thank you in advance
