### ISSUE TITLE
Help Us Adjust The Default Size Of All Post-Cards Across https://steemgigs.org

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#36]
We would like to reduce the default size of all post-cards or thumbnails across https;//steemgigs.org. The new default size should apply across all genre of post-cards all across the website. 

Here is a screenshot displaying how the look/size of post-cards on the website:
![steemgigs issuess](https://user-images.githubusercontent.com/23729959/38168143-099b4408-3577-11e8-8b85-6cbb2f9c5e3e.png)

We would like the new default dimensions for post-cards to be 233 x 313 (horizontal x vertical)
The essence of this is to make cards look a bit smaller, smarter and to make better use of space. 

Every other existing facet of post-cards should stay the same. Only the size of the cards should be reduced a bit from what it currently is.

Here is a shot of the how it should now look. Please use the screenshot as guide to get estimated measurement for image area.
![steemgigs issues](https://user-images.githubusercontent.com/23729959/38168103-098a8e02-3576-11e8-8ada-dcc58cb83724.png)

> Note that all that should change is the default size of "the external rectangular boundary" of post cards. Every other detail or styling should remain the same.

**Comment by tobias-g1** [comment]
Are you happy with the current size of the postcard? Can we close this one? @surpassinggoogle
