### ISSUE TITLE
Help Us Limit The Number Of Rows (For Post-Cards) For Each Segment Of The Homepage Of https://steemgigs.org, To 2 Rows Each.

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#38]
In this task, we would like you some adjustments to the formation of the homepage (upon login) of https://steemgigs.org
The homepage is suppose to display several segments, with each segment having its own catalog. 

> A catalog is a display of rows of post-cards specific to a certain segment.

On https://steemgigs.org, the homepage (upon login) actually has several segments e.g the first segment is #steemgigs which contains a catalog of gigs or services only. The next segment is #featuredsteemgigs, that is suppose to display a catalog of features-gigs only. Then this is followed by #gigrequests, which displays a catalog of  custom-requests only. There is also #surpassinggoogle and #testimonials etc

## The Issue
It is not very obvious that the homepage contains other segments as the most prominent segment is #steemgigs as it the first segment on the page. This reduces site navigation to the other beautiful facets or segments of SteemGigs. 
The reason is; the first segment #steemgigs displays a growing number of rows of post-cards, that for users to get to the other segments of the homepage just below, they would have to scroll down and down for long periods and the probability of users doing this reduces as the number of gig-cards keep growing etc.

## Expected Outcome Of Task At Hand
We simply want you reduce the number of rows for #steemgigs to two, with the option to "view more" (which already exists). As users click on "view more" however, it should lead them to a "new tab" showing only a catalog for #steemgigs, with a more elaborate endless row of gigs-cards only, without showing any of the other segments. 

> Every other thing remains the same.

Now, you will also apply the same adjustment to **all the other segments** existing on https://steemgigs.org homepage (upon login)
i.e each segment should maintain its catalogs, with a maximum of 2 rows (of post-cards each); so much so that when users click on the "view more" button for each segment, they are taken on a "new tab" containing only the catalog for the specific segment, with countless number of rows and an eventual "view more" option.

**The two paint mock-ups will explain better.** 
![steemgigs issues15](https://user-images.githubusercontent.com/23729959/38246421-53b99a4a-3774-11e8-9323-5d0d2e716c23.png)

![steemgigs issuess15](https://user-images.githubusercontent.com/23729959/38246455-704eec82-3774-11e8-9334-92b618158a60.png)

> **Note that most of the features to work with are already in existence on the site.** 
> You are simply going to reduce the rows on each segment on homepage (login) to 2 each, with the option to "view more", but whenever people click on "view more", they should be led to a "new tab", which should show only content (a catalog) of selected segment, with countless number of rows

**Comment by tobias-g1** [comment]
I believe this has been resolved @surpassinggoogle
