### ISSUE TITLE
Help Us Adjust The Format (Display) Of The #testimonials Post-Cards, To Look Similar To Post-Cards From Other Segments Of https://steemgigs.org

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#39]
For this task we will like to adjust the format or the way the post-cards under the #testimonials segment on the https://steemgigs.org homepage displays, to now follow a similar format to all other post-cards (of other segments) all across the website.

## Current Behavior
First off, #testimonials post-cards look like this:
![steemgigs issuess16](https://user-images.githubusercontent.com/23729959/38248412-d83a6f6e-377a-11e8-8f6c-21b011b108af.png)

Note that you are able to expand this post-card by clicking on it and this will take you to a full view of the post. However, unlike all other post-cards (of other segments), with the #testimonials post-cards, you can also read the full post right there on the card, by scrolling up and down and sideways.

## Expected Behavior
After this task, we will want the #testimonials post-cards to now take a similar format to post-cards from the other segments of https://steemgigs org e.g similar to the #steemgigs post-cards etc
**Here is a mockup showing how we now want it to look:**
![steemgigs issuesss16](https://user-images.githubusercontent.com/23729959/38248585-72dd98de-377b-11e8-9d22-28b61b1c655c.png)

> To read in full view, one can either click on "read full testimonial" or right click on the tab to "open in new window".

Now, this will also lead to a slight adjustment to the **[#testimonials specialized editor](https://steemgigs.org/create_testimonial)**. 
**Here is a mockup showing the slight adjustment to this editor:**
![steemgigs issues16](https://user-images.githubusercontent.com/23729959/38248654-be4235c8-377b-11e8-8588-44ad26f33cb3.png)

**Comment by tobias-g1** [comment]
I believe this is resolved? @surpassinggoogle Can we close this?
