### ISSUE TITLE
The Wallet, Settings and Invite friends Button aren't work at all.

### ISSUE THREAD

**Issue by evalina1** [steemgigs/steemgigs#42]

**Comment by surpassinggoogle** [comment]
Hi evalina, are you on steemit too? Are you are programmer?

**Comment by evalina1** [comment]
Yes, I am a user of Steemit. I like to work with utopian.io. I am a bug
hunter and suggest useful things to make a application much better.

**Comment by AneilPatel05** [comment]
I am a programmer and interested in working with you on this.

**Comment by surpassinggoogle** [comment]
@AneilPatel05 yes, i know, we have had conversations in the past. You can join [here](https://join.slack.com/t/steemgigs/shared_invite/enQtMzQ3MjM1NTQyNTEyLWE5MDk3ZmNlZTA1OGUxZWVjMzNhYTAyZTU3NzZkZGQyNjRiNTM0MGIwYjNhZTI5NmYyYTgwNzVjMzAyN2JlYzI)
