### ISSUE TITLE
Please Help Us Adjust The "Display" Of The Search Function On https://steemgigs.org

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#44]
> We would like the search function to display results on page, instead of bringing up a separate screen. 

## Current Behavior
When you click on the search function, it pulls up a new screen, which blocks you from all other facets of steemgigs.org and shows you a listing of post-cards related to your search phrase. With this, it cuts away your ability to navigate other parts of the website unless you close or minimize the search screen. Also the display of post-card displays differently than normal post-cards all across steemgigs.org, with rectangles (wider and shorter), thus, skipping out some interest details of the post-cards e.g image thumbnails, potential payout, upvote icon, comment icon, resteem icon etc This also limits the quality of overall search experience. (Note also that steemgigs.org is steem-based, thus, essential to our style is curation and engagement capabilities.)
This is the current display upon typing in a search phrase, after clicking on the search icon:
![image](https://user-images.githubusercontent.com/23729959/38766307-aa14c9be-4002-11e8-81f2-cfdcb95e72e8.png)

## Expected Behavior

> Note: The search function is not yet at optimal levels, so it doesn't really have "refined" capability or "filters" yet. Current search can mostly searching using keywords (e.g words appearing in title etc) as well as **"usernames"**.

**Thus for now let's focus on this**:
At the end of this task, **"search"** should happen right on the page. e.g, if a user, clicks on the search icon, it should present a box on page, into which they can type in search phrases and if for instance, the user types in the word "steem", the search results should display right there on the same page, showing a catalog of every gig-cards or post-cards from all across steemgigs.org, that have the word "steem" in title etc 
Gig-cards or post-cards should ofcourse maintain display like normal (tall rectangles) i.e
![steemgigs new editsssssssss](https://user-images.githubusercontent.com/23729959/38766415-835488ee-4004-11e8-8016-3c17220a7739.png)
**

> Note: It can display 4 post-cards per row, with options to "view more".

**

## Style Guide
For this particular task, we are simple working on the display of search results and not search algorithm, thus, the search algorithm and all that pertains to it, should remain the same.

**Comment by tobias-g1** [comment]
This has been resolved, further work will be completed in #69
