### ISSUE TITLE
Steemgigs Messaging Button not Responding.

### ISSUE THREAD

**Issue by joshuaattat** [steemgigs/steemgigs#5]
#### Expected behavior
When I click on the messaging icon, its supposed to take me to a section where I can message people or see previous messages from people on the Steemgigs platform.

#### Actual behavior
When I click on the messaging icon, nothing changes; the same page remains.

#### How to reproduce

![sg 2.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520721012/qfm5pqcwxwmsn82m22md.png)

![msg 1.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520720878/yzpfixtr2r8zfpce1spa.png)

Simply log in to the [Steemgigs website](http://steemgigs.org) and click on the messaging icon on the top right hand panel.

* Browser: Google Chrome
* Operating system: Windows 7    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@joshuaattat/steemgigs-messaging-button-not-responding">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jalasem** [comment]
It's not a bug, it's a feature yet to be implemented, it's on our roadmap
