### ISSUE TITLE
Post payout on gigAction doesn't display payout after 7 days

### ISSUE THREAD

**Issue by tobias-g1** [steemgigs/steemgigs#58]
Looks like I missed this one, adding here as a note to remember...

![image](https://user-images.githubusercontent.com/17148879/51280836-a007b200-19d8-11e9-8a40-b016107d001c.png)

**Comment by surpassinggoogle** [comment]
Yes, the post card itself already shows post7days payout but when the post is expanded to full view, it doesn't
