### ISSUE TITLE
Proposed SteemGigs FAQ

### ISSUE THREAD

**Issue by Pope19** [steemgigs/steemgigs#6]
After using Steemgigs for a while i noticed that there wasn't a FAQ on the web-page for new users to help them get acquainted with how to navigate round the site and how buyers and sellers can interact properly on SteemGigs.

Having an FAQ on the website will increase user confidence as it is often sought after and serves as a source of first communication on any service based website.

Here is a link to the FAQ
[Link](https://www.dropbox.com/s/lf3r5i21hgl3kjv/SteemGigs%20FAQ.docx?dl=0)

Constructive criticism and suggestions are welcomed.

**Comment by tobias-g1** [comment]
Dropbox link no longer accessible
