### ISSUE TITLE
Add follow modal after user logs into prompt to follow SteemGigs (Additional Bounty Of 10 Steem + 150 TEARDROPS)

### ISSUE THREAD

**Issue by tobias-g1** [steemgigs/steemgigs#64]
When users attempt to login, we would like a simple portal to show up (as part of the login process), if they haven't followed @steemgigs yet. 

This portal should display a 'follow' @steemgigs tick-button. This button should be ticked by default. Users will be able to un-tick it at will, if they do not intend to follow @steemgigs

Extracted from https://steemit.com/steemgigs/@surpassinggoogle/task-request-kindly-help-us-tend-to-14-micro-programming-tasks-to-enhance-the-overall-steemgigs-org-ux

**Comment by tobias-g1** [comment]
Another option to consider here might be to include it within the profile menu, this is was SteemHunt does and overall I believe this creates a less obtrusive experience than providing a modal with all of the time. 

The following shows what it looks like on SteemHunt:

![image](https://user-images.githubusercontent.com/17148879/52312250-cbf7d100-29a1-11e9-9fb3-fc6858da16ab.png)

What do you think? @surpassinggoogle

**Comment by surpassinggoogle** [comment]
Yes, that is fine.
