### ISSUE TITLE
Add Auto-Save Posts & Comments.

### ISSUE THREAD

**Issue by tobias-g1** [steemgigs/steemgigs#66]
In this task, we simply want you to do the following:

Add a function that auto-saves 'input' to our editors. This may be made to happen in-browser, like in the case of steemit.com i.e whatever has been typed into the post-editor should remain intact, even where users refresh the page or where their PC suddenly turns off. This auto-save function should also apply to comments. (Kindly explore steemit.com for ideas)

Taken from here: https://steemit.com/steemgigs/@surpassinggoogle/task-development-help-us-add-refine-search-capability-to-the-steemgigs-org-search-and-other-tasks

**Comment by surpassinggoogle** [comment]
The primary focus for this task is to work on 'autosave' or draft so users don't lose their work (prior to publishing). The 'edit' feature can come much later

**Comment by tobias-g1** [comment]
Moved edit to #93
