### ISSUE TITLE
Proposed SteemGigs help center for buyers

### ISSUE THREAD

**Issue by edikanefanga** [steemgigs/steemgigs#7]
After browsing the SteemGigs website for a while, I couldn't help but notice the absence of a help center for buyers and sellers respectively which is meant to cater for questions and the well being of the sellers and buyers on the platform.

The inclusion of a help center for buyers will help in the speedy navigation of the SteemGigs website by buyers and also help in answering pending questions on the minds of buyers.

Here is the link to the help center
[Link](https://www.dropbox.com/s/ms7acwzif19kcqk/SteemGigs%20help%20center.doc?dl=0)

I am open to a wide range of suggestions and constructive criticism

**Comment by tobias-g1** [comment]
A simple FAQ page wouldn't take long to build, probably less than an hour, would you like to include any of #7 #14 #23 in it? Are they still relevant? or would you prefer us close these tasks and you begin to create a new FAQ set? @surpassinggoogle

**Comment by surpassinggoogle** [comment]
portions of it still has relevance. overall, I will need to even edit a faqs I wrote some time in the past. But yes, you can add this one and a little read more link at the bottom leading to this post: https://ulogs.org/@surpassinggoogle/the-grand-picture-the-detailed-faq-s-for-https-steemgigs-org-and-all-the-answers-please-bookmark-this
