### ISSUE TITLE
Steemgig Comment Bug

### ISSUE THREAD

**Issue by NileshBakshi** [steemgigs/steemgigs#8]
# Expected behavior
When you comment on any post on steemgigs your comment should be shown.

# Actual behavior
When I commented on posts on steemgig with only 1 comment beforehand and proceeded to submit my comment the comment already there gets duplicated but I cannot see my comment. This only happens on steemgig site and not on steemit. 

# How to reproduce
1. Find any gig with only a single comment on it.
2. Post your comment on the gig and it will not be shown but the comment previously there will be duplicated.

* Browser: Google Chrome 64.0.3282.137
* Operating system: Android OS 6.0.1

# Recording Of The Bug
https://youtu.be/JPURVM6kF38
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@naysayer/steemgig-comment-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemgigs** [comment]
> Thank you alot @NileshBakshi for your contribution. It is so valued. We do want testimonies of SteemGigs being built by everyone. We truly want to represent "everyone has something to offer", hence we value this alot.

# To The Developer Who Picks Interest In Handling This.
This isn't exactly a bug but **enhancement** is essential. What happens here is, on https://steemgigs.org, when you reply to a post, the comment doesn't appear in the thread **"on the spot"**, like is the case on [steemit](https://steemit.com) or busy.org. 
All that is needed to view the comment is to **"refresh the page"**. As a result, users of SteemGigs, will think their replies never got published and will try to submit reply again, leading to a replication of comments. 

Thus, we need an enhancement to where, replies appear "on the spot", after submission, without having to reload the page. 

> See how replies work on Steemit to grasp fully

[Visit with us on Slack](https://join.slack.com/t/steemgigs/shared_invite/enQtMzMxNDIzMzM5MTkxLWRhNDgyMjc5YjNmZjJmMWYzNGU3ZTcxMjFjMTU5YWI5ZGNhMjA5ZDdlNWIwNjcwNjRiMzc3NDRiMzk2MDU4MzI) for further development discussion

> Make sure to submit your contributions using [Utopian](https://utopian.io/project/steemgigs/steemgigs/github/111312577/all) as they reward approved open-source contributions

**Comment by AneilPatel05** [comment]
It is a osmetic change. 
I am learning vue.js now. let me see if I can help.

**Comment by tobias-g1** [comment]
This is still an issue, able to replicate.
