### ISSUE TITLE
Kindly Help Us Add A Microtasks Segment To Our Homepage (upon login) And A Corresponding Microtask Post-Editor

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#87]
<html>
<h1>Repository</h1>
<ul>
  <li><a href="https://github.com/steemgigs/steemgigs">Steemgigs (Front-End)</a>&nbsp;</li>
  <li><a href="https://github.com/steemgigs/steemgigsServer">SteemgigsServer (Back-End)</a></li>
</ul>
<blockquote>&nbsp;&nbsp;SteemGigs: A Revolutionary Decentralized Freelance Marketplace With Its Own Knowledge-Bank. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</blockquote>
<blockquote>A revolutionary freelance marketplace built on the steem blockchain that removes all barriers to entry, by implementing an "untalented &amp; community paradigm". &nbsp;&nbsp;</blockquote>
<h1>Details</h1>
<p>This task covers the following:</p>
<ul>
  <li>Help Us Add A Micro-tasks segment to our homepage (upon login) and a corresponding micro-task editor</li>
</ul>
<p>We are keeping this task simple at this stage. Our aim within this task, is simply to give users and contributing developers insight into another aspect of steemgigs.org called 'the Microtasks segment'.</p>
<p>On steemgigs.org, we believe that 'everyone has something to offer', whether you consider yourself an expert or a non-expert. Even if you aren't very confident yet about your talents or about offering your service, you can participate in microtasks to hone your existing skills and grow in confidence. However minute, you contribution may appear, you will have played a role in historical history, by helping someone build their dream.</p>
<p>Besides, we want to use our microtasks segment to highlight a 'pay-with-vote' paradigm, exclusive to the steem ecosystem. It is essential to show these beautiful aspects of steem to the mainstream public and remind existing steemians of this too.</p>
<p>Microtasks in general may payout micro-payments. This may not impact the reward pool much and can be paid 'with votes'. In general, what has been rewarded on the steem blockchain is 'value' moreso than content and it essential to paint this using steemgigs.org, as one core paradigm of steemgigs.org is 'steem growth'.</p>
<h2>Task Proper</h2>
<p>On our homepage, you will notice that we have a 'create' button, leading to a bunch of editors as seen below:</p>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVNERDRYVZxuLtUMQdyykwgJux1KjiHDU252o2T1ziPKaiqXHwEEU6aojSB4kRSK4XeAMv49CiJyEMMyuehqLTjeAbDGVFm57ZSAjNSqC6cr171CGAQTG?format=match&amp;mode=fit&amp;width=640" width="640" height="360"/></p>
<p><br></p>
<p>We would like to add one more item to the list called 'Create Microtasks', which allows users to create microtasks.&nbsp;</p>
<p>To build this editor, you will simple need to replicate the '<a href="https://steemgigs.org/create_gig">Create a gig</a>' editor, with some tweaks.</p>
<p>The '<a href="https://steemgigs.org/create_gig">Create a gig</a>' editor currently looks like this:</p>
<p><img src="https://steemitimages.com/p/2VZXybTSZJq1AreaDn1D7Jp7ZEvgLC9TvJctofX1ChMgSZoqBjhp3wxFkWQEjPt2L3wVAPeZ8xK2fCbq9vmqJ9NV6rmv5f2yjYWVRHrsfkZv1iSLm72FfxTDWCyruGfJXaJTsGiZ4GsayRwacDn1HuhmDSn?format=match&amp;mode=fit&amp;width=640" width="640" height="566"/></p>
<p>We will be following a similar template in building the Microtasks' editor, to create something like this:</p>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVNMwgmWcG6jm2yjVwmdongTDDdNeE4jNrhkQYY2hi1XBqLmp74gD94oQ7vsomBgf95H2RpmFgqXFsQYJMNBD2WiPi2vn35L4S1ffujKStxqPsoRFzcrS?format=match&amp;mode=fit&amp;width=640" width="640" height="610"/></p>
<p><br></p>
<p>Notice that the new flow for the Microtasks' editor is:</p>
<p><strong>description &gt; pricing &gt; requirements &gt; duration &gt; no. of applicants &gt; no. of entries per applicant &gt; requirements' sample</strong></p>
<p><br></p>
<p>I will now explain below the various aspects of the Microtask editor, using the images below:</p>
<h3>Description:</h3>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVNJQPekdGe667XgByQjWkXkQuW53zZGHHmetE7ifV7yokVbwqDGYtqddEuACpurW4nT1Jhi2Rg8odgTcGEWBEAkLduWeZWaXJDrThzHY4NAyeZWLKJBY?format=match&amp;mode=fit&amp;width=640" width="640" height="400"/></p>
<p><strong>Here is the raw header text:</strong> [You can build aspects of your dream by creating a microtask. A microtask can take different forms. In most cases, participants are required to carry out a simple action e.g join a telegram, subscribe to my YouTube, leave a feedback on my post etc You can pay with SBD, Steem, Steem Power or with a Steem Upvote.</p>
<p><strong>Please Read:</strong> When it comes to displaying microtasks on steemgigs.org, we give priority to 'certified uloggers'. See our <a href="https://ulogs.org/discover">list of 'certified uloggers'</a>. To get certified, <a href="https://ulogs.org/@ulogs/ulog-become-a-certified-ulogger-today">click here</a>.]</p>
<h3>Payment:</h3>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVPDc5CrkfVoKMYsNrMwNe2jZiMHKH7uMajQchgDvQiFrGco5p5FV4q1ThJJL7Ycj5xffdLgYvZkh2YpUxdYsqvziAGDgtHtAysC3cAngoYWKwxmCRtVt?format=match&amp;mode=fit&amp;width=640" width="640" height="212"/></p>
<blockquote>Please note: the 'payment' column should accept decimal entries e.g 0.01 to integrate the new 'steem upvote' option</blockquote>
<h3>Requirements:</h3>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVNDfAGg4it9kDhgW5K3UKPWQt9BR8TFQoMvhEgmPU3L7EvtJKRdnck8kWWFNMpAqqp4Hn435FpwicurNYWrzkvWtGADUXSPvbaYe1RJXFgbRdai5kRF4?format=match&amp;mode=fit&amp;width=640" width="640" height="153"/>&nbsp;</p>
<h3>Duration:</h3>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVN5cN3n4HB2xtD1qP7MCxGmf1k9w22kJqZbEdbgBBnLnJvZiUGdfww6MxSHfM9tC1gqT31TWxYWVTds2NgggLNC6SaQrNCVd36EUaiHJuhtBbHnQ47Vp?format=match&amp;mode=fit&amp;width=640" width="640" height="102"/></p>
<h3>No. Of Applicants:</h3>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVN5x5G9GDzkajj7SCAHN9yFwdwhkoFbimCH9aLUrYxbF3af5vvFY4epBtusDjFZKm9XzG4EjQk4snf5vMRqyTqwWZbURVVC6tZmWXMrzgc2oiYqw5JpW?format=match&amp;mode=fit&amp;width=640" width="640" height="102"/></p>
<h3>No. Of Entries Per Applicant:</h3>
<p><img src="https://steemitimages.com/p/k75bsZMwYNtze9xHvT6xWCdz7q3QGD35ZKdaPpVrFksWkBQdbfMCHyDo9mQNB9Yyx2yx8EjybmSkvphMRGrte8vDTirhdsi8Fii6C5iMNjxBEok2Eie8DKF4u2nMzPB822o3ZmdxcJzwqjq3biGBy2LMJiEGzYZQi?format=match&amp;mode=fit&amp;width=640" width="640" height="102"/></p>
<h3>Requirements' Sample:</h3>
<p><img src="https://steemitimages.com/p/AmRc67RgYaWTCbCd1L4AQP82AFWYYzZC15DpSZWeSYgzVP9wVb7Eo2umrG74ZPWkDL3q14UjoKfEFD9BR4Mb8pQ5x6BAsfnsUL3TdQz7TFVLhciPJnmVPswttKHhSfLuTmPLnnGuFntmuaRb8ftFPLyEMA8SHrX8?format=match&amp;mode=fit&amp;width=640" width="640" height="201"/></p>
<p><br></p>
<p>This microtask editor just like the 'create a gig' editor, will determine the format of its resulting posts.&nbsp;</p>
<p>Look at the post below, which was created using the 'create a gig' editor, to understand better:</p>
<ul>
  <li>https://steemgigs.org/steemgigs/@autofreak/create-a-masterpiece-business-plan-for-you-in-4-days-96-hours</li>
</ul>
<p>Now, that we have created the microtasks' editor, we will need to add a new column to our homepage (upon sign-in) to display a catalog of microtasks.&nbsp;</p>
<p>We will like you to create a new row for this, just under the 'Steemgigs Request' row, on our homepage.</p>
<p>The next part of the task is to tweak the resulting post-cards, for posts created via the microtasks editor. We now like such post-cards to look like this:</p>
<p><img src="https://steemitimages.com/p/k75bsZMwYNtze9xHvT6xWCdz7q3QGD35ZKdaPpVrFksWkDxx4dc5YeWgUaV61t9iu4XWQsXiXs81ETGVKMB4H6z7sLNbR2debSzFpbNVnJDkn59ApS2SiFnSTXwgj2UfDVCeAY7uftVTwbuwLoa2GJYex88WvvVoL?format=match&amp;mode=fit&amp;width=640" width="640" height="360"/></p>
<blockquote>When users click on the 'Apply' button, it should expand the post.</blockquote>
<h1>Component</h1>
<ul>
  <li><a href="https://github.com/steemgigs/steemgigs">Steemgigs (Front-End)</a>&nbsp;</li>
  <li><a href="https://github.com/steemgigs/steemgigsServer">SteemgigsServer (Back-End)</a></li>
</ul>
<p>Analyzing the <a href="https://steemgigs.org/create_gig">'create a gig' editor</a> is a good starting point.&nbsp;</p>
<p>If you would like to take up the task, kindly indicate your intention in the comment section below. Where you get stuck, we can always discuss possible solutions, logic etc We just may find answers!</p>
<blockquote>Overall, carry out the task according to your preference and &nbsp;expertise, submitting a pull request and thereafter create a post highlighting your contribution, following Utopian's guidelines for Development (contributions) as this post is likely to be curated by utopian.io</blockquote>
<h1>Deadline</h1>
<p>2 days</p>
<h1>Communication</h1>
<p>You can contact me on:&nbsp; &nbsp; &nbsp; &nbsp;</p>
<ul>
  <li><a href="https://t.me/teardrops_smt"><strong>Telegram </strong></a><strong>(username: </strong><a href="https://steemit.com/@surpassinggoogle"><strong>@surpassinggoogle</strong></a><strong>)</strong></li>
  <li><a href="https://discord.gg/7bUFymy"><strong>Discord</strong></a><strong> (username: surpassinggoogle#1660)</strong></li>
</ul>
<blockquote>You can also indicate interest by leaving a comment underneath this post or on Github.&nbsp;</blockquote>
<blockquote>It is recommended that we are able to&nbsp;discuss, for a better understanding of the task.</blockquote>
<h1><strong>Github</strong></h1>
<ul>
  <li><a href="https://github.com/steemgigs/steemgigs">Steemgigs (Front-End)</a>&nbsp;</li>
  <li><a href="https://github.com/steemgigs/steemgigsServer">SteemgigsServer (Back-End)</a></li>
</ul>
</html>

Find clearer images here:
https://ulogs.org/steemgigs/@surpassinggoogle/task-request-kindly-help-us-add-a-microtasks-segment-to-our-homepage-upon-login-and-a-corresponding-microtask-post-editor

**Comment by tobias-g1** [comment]
Would this be creating a new editor? 

Would this also include adjustments to the feed (home page) to display these items?

**Comment by surpassinggoogle** [comment]
yes.  it will but I will try to keep it simple for a start. Mostly so user can see that it is in the making. I will try to complete this issue later today

for editor I am think of just converting the untalented editor. that editor is just an extra editor to post to the steem blockchain. so perhaps, it can be converted. then microtasks will have a column on the homepage. I am also thinking that this editor will allow anyone to create a microtask but the display column will be available only to certified uloggers, to create further incentive for people to get certified. ofcourse anyone can particpate in tasks.

**Comment by tobias-g1** [comment]
A few points to consider in your decisions:

1. It's not necessarily more work to add a new one if you still believe there is still value in the current #untalented editor in its current form. 
2. What is the difference between a microtask and a gig request? Can you provide me with a few examples of micro-tasks, please? Without that information, it's hard to comment on the restrictions you should make.

**Comment by surpassinggoogle** [comment]
Okay. We can remove untalented editor, since its really displaying on steemgigs and the steemgigs.org/surpassing-google has a version of the editor as well. In truth, the plan was for steemgigs.org/surpassing-google post should display on the website in its own space, sort like a subdomain that displays these post, but that will come in the near future.

For microtask, it is a bit different. Custom requests don't happen too often as these are usually big gigs need like real pro help and expertise etc e.g help me develop a website etc

For a microtask, in most cases, users can make use of this feature more frequently for simpler tasks e.g like my facebook post or subscribe to my youtube channel etc There is an ecosystem for this on steem, especially since the payments involved in many cases are micropayments to many participants and may not take much from reward pool and subject to task creator stake etc This feature will help us highlight other beautiful aspect of steem like pay with vote.

So users will be able to receive small payments with votes. Normally participants can participate in comment section, with screenshots of their actions, then owner of the task pays them with SBD ,steem, sp or vote. 

For now it will be kept simple then evolved overtime

**Comment by surpassinggoogle** [comment]
I have now added the complete task. It is kept simple. Almost a replication of the 'create a gig' editor.
https://github.com/steemgigs/steemgigs/issues/87
