### ISSUE TITLE
Add Resteem Button & Functionality To Expanded Posts.

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#94]
Post cards across steemgigs.org have a functional resteem button. We will like to add this button to all posts across steemgigs.org

Currently, expanded posts don't have a resteem button as seen below:
![image](https://user-images.githubusercontent.com/23729959/52536857-b536ed00-2d9a-11e9-92ac-9f8feca53972.png)

**Comment by tobias-g1** [comment]
This is resolved, also noticed that a user had the ability to attempt to reblog their own posts, I disabled this to create a clearer UX and overall prevent errors.

**Comment by surpassinggoogle** [comment]
Thank you alot bro.
