### ISSUE TITLE
Help Us Design/Re-design The steemgigs.org Landing Page. (Additional Bounty Of 50 STEEM)

### ISSUE THREAD

**Issue by surpassinggoogle** [steemgigs/steemgigs#98]
<html>
<p>&nbsp;</p>
<h1>Repository</h1>
<ul>
  <li><a href="https://github.com/steemgigs/steemgigs">Steemgigs (Front-End)</a>&nbsp;</li>
  <li><a href="https://github.com/steemgigs/steemgigsServer">SteemgigsServer (Back-End)</a></li>
</ul>
<blockquote>&nbsp;&nbsp;SteemGigs: A Revolutionary Decentralized Freelance Marketplace With Its Own Knowledge-Bank. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</blockquote>
<blockquote>A revolutionary freelance marketplace built on the steem blockchain that removes all barriers to entry, by implementing an "untalented &amp; community paradigm". &nbsp;&nbsp;</blockquote>
<h1>Details</h1>
<p>In the task at hand, we will like you to help with the following:</p>
<ul>
  <li>Help us design/re-design our landing page or homepage (prior to login)</li>
</ul>
<p><br></p>
<p>We would like to add some more segments to our landing page or homepage (prior to login), in relation to the different core aspects of https://steemgigs.org</p>
<p>We want users to be able to have in-depth insight into what steemgigs.org is about, even prior to signing-in/signing-up.&nbsp;</p>
<p>In this early stage, our landing page isn't only targeted at users but also at potential supporters, venture capitalists, steem-power holders etc who may not be opportune to sign-in, so that they can have an overview of our vision and more.&nbsp;</p>
<p>Overall, we want our landing page to be powerful both content-wise and design-wise.&nbsp;</p>
<p>Below, i will be relating in detail, what we are trying to build, using images. Our landing page consists of rows, from top to bottom. Some such rows already exist on our current landing page as seen below:</p>
<p><img src="https://steemitimages.com/p/C3TZR1g81UNaPs7vzNXHueW5ZM76DSHWEY7onmfLxcK2iQT3N5pwxzN9ddgPKTv87UezafzFTVHAULgMvfqCvczHXvh63GzckonmCDK2KJE9ko3GGGrvafp?format=match&amp;mode=fit&amp;width=640" width="640" height="360"/>&nbsp;</p>
<p><br></p>
<p>You can enhance existing rows and add new ones or build the landing page afresh. Regardless, ensure that the design is consistent and considers UX.&nbsp;</p>
<p>I will now be posting images (mock-ups), in a sequence (from top to bottom), indicating the different rows that should make up our landing page/homepage (prior to login):&nbsp;</p>
<h2>Image 1 (topmost):&nbsp;</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52727058-6635c580-2fef-11e9-9168-9879b06e34a3.png" width="1366" height="666"/></p>
<blockquote>Kindly chose a background color that you deem fit as per design. We want the welcome header-text to be really pronounce and the land page to have a sharp feel for a better UX. In the long run, this topmost area will display a realistic-photo slide, featuring our community members.&nbsp;</blockquote>
<h2>Image for row 2:</h2>
<h3><img src="https://user-images.githubusercontent.com/23729959/52727211-b3199c00-2fef-11e9-94db-215d6facbb6f.png" width="1366" height="654"/></h3>
<blockquote>This row will have a YouTube video embed. We don't have the exact YouTube URL to embed yet, thus, you can just use this as default: https://www.youtube.com/watch?v=xeLYLA6C2AE&nbsp;</blockquote>
<p><strong>Now, here is the raw text for this row:&nbsp;</strong></p>
<h2>Things You Can Do On STEEMGIGS&nbsp;</h2>
<h3>Create A Gig&nbsp;</h3>
<p>Whether you an expert or non-expert, you can offer a service in exchange for STEEM, STEEM Dollars, Steem Power or <em>'for free'</em>. SteemGigs has an <a href="https://ulogs/org/steemit/@surpassinggoogle/steemit-s-untalented-is-in-beta-participate-freely-because-every-participant-in-this-contest-will-win-something-no-losers">un(dis)talented paradigm</a>. This means that on SteemGigs, everyone has something to offer.&nbsp;</p>
<h3>Locate A Gig&nbsp;</h3>
<p>We maintain a repository of gigs (services) offered by '<a href="https://discord.gg/wWrnSXK">a community of reputable great minds</a>'. We have a vibrant community, heartily seeking to help you '<em>build your dream</em>'. We don't only offer you talents; we offer you a like-mind, a SteemGigger, a dream-builder, a brother. Visit https://steemgigs.org, to locate that special someone.&nbsp;</p>
<h3>Create A Custom Request Or Microtask&nbsp;</h3>
<p><em>"Do the dreaming, leave 'the building' to us"</em>. Where you can't find the 'exact gig' that fits your need, you can create a <strong>'custom request' or 'a microtask request'</strong> and we will actively seek out reputable great minds from our community who can help.&nbsp;</p>
<h3>Create Content&nbsp;</h3>
<p><em>On STEEMGIGS, content is queen</em>. A core aspect of SteemGigs is <a href="https://steemgigs.org/surpassing-google">our knowledge-bank</a>, a repository of niche-based information borne out of experience. We welcome content-contributions for our users. This content ranks in the search engines and is published to the steem blockchain, before a large community.</p>
<p>Where your content attracts likes (upvotes), you earn in Steem or Steem Dollars and in the near future, <em>the teardrops smart media tokens.&nbsp;</em></p>
<h3>Curate And Interact</h3>
<p>On SteemGigs, everyone has something to offer. You can also visit SteemGigs for the sole reason of interacting with its community. One way of doing so is by curating content. This means that you can find posts to read, like (upvote), leave comments on etc right there on https://steemgigs.org&nbsp;</p>
<h2>Image for row 3:&nbsp;</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52831697-83ae8080-3110-11e9-9c6d-629fd8ebca09.png" width="1366" height="672"/></p>
<p><br></p>
<p><strong>Here is the raw text for this row:</strong>&nbsp;</p>
<h3>How We Stand Out?&nbsp;</h3>
<p>You have successfully reached STEEMGIGS, a revolutionary freelance services marketplace &amp; social network connected to a decentralized steem blockchain, with the power of Fiverr, Upwork &amp; Freelancer combined. SteemGigs removes all barriers to entry in relation to 'building a dream', by implementing an 'untalented &amp; community paradigm', in association with a token economy.&nbsp;</p>
<p>Whether it is an innovation, vision, enterprise or business and it is yours, we consider it 'a dream' and it is about 'your dream' for us. As a result, we will go beyond just getting you the right freelance services. We want to play an active role in historical history as part of your noble dream.&nbsp;</p>
<p>On STEEMGIGS, everyone has something to offer.&nbsp;</p>
<h3>How Else?</h3>
<ul>
  <li>We have a token economy that allows users to earn for their content, in addition to 'services rendered'. (This applies to both clients and freelancers).&nbsp;</li>
  <li>No third-parties merchants and its associated fees.&nbsp;</li>
  <li>No censorship. (meaning your gigs can't be deleted).&nbsp;</li>
  <li>We have an established and reputable community.</li>
  <li>We know our community and it is an actual community.&nbsp;</li>
  <li>Steemgigs is content-driven.&nbsp;</li>
  <li>There is room for non-experts, who want to be freelancers</li>
  <li>You can find free GIGS.&nbsp;</li>
  <li>You can earn from doing microtasks.</li>
  <li>We are affiliated to a larger community of steemit.com users.&nbsp;</li>
  <li>You can pay/earn for services for/with SBD, Steem, Steem Power or 'via a steem upvote'.</li>
  <li>We have a knowledge-bank, that maintains a repository of expert-knowledge, borne out of real-life experiences.</li>
  <li>Your STEEMGIGS content ranks in the search engine too</li>
  <li>If you are a client, you get more than a freelancer. You get a like-mind, a reputable great mind, a dream-builder and brother.</li>
  <li>You can have a stake in the company by virtue of the teardrops SMT.</li>
  <li>Certified users can earn UI-perks and other exclusive benefits</li>
  <li>etc&nbsp;</li>
</ul>
<h2>Image for row 4:&nbsp;</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52805257-28a16d00-30c1-11e9-96c1-75dcaaa577dc.png" width="1366" height="440"/></p>
<blockquote>These thumbnails will be placeholders for now or can simply link to 'https://steemgigs.org' for now. In the long run, these thumbnails will lead to a respective page.</blockquote>
<h2>Image for row 5: &nbsp;</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52829163-a176e800-3106-11e9-8dac-3e4c2e89f0ce.png" width="1366" height="530"/></p>
<blockquote>This row already exists on https://steemgigs.org and already has the right paths. You can enhance it to make it consistent with the new design or you can build it afresh.</blockquote>
<h2>image for row 6:</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52831472-befc7f80-310f-11e9-9447-febd07e5468e.png" width="1366" height="280"/></p>
<blockquote>The 'Get Started' button should alert people of the need to sign-in or sign-up</blockquote>
<h2>image for row 7:&nbsp;</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52878557-e5fe9400-3197-11e9-8c50-1553f984a9ad.png" width="1366" height="444"/></p>
<blockquote>The <strong>'Publish Content To Our Knowledge-Bank' button</strong> should to 'https://steemgigs.org/surpassing-google', while the <strong>'Read Content From Our Knowledge-Bank' button</strong> should lead to 'https://steemgigs.org/categories/surpassinggoogle'</blockquote>
<p><br></p>
<p><strong>Here is the raw text for row 7:&nbsp;</strong></p>
<p>Everyone participant of our ecosystem will eventually become a 'dream-builder' (SteemGigger), building their dreams and those of others. To accomplish this, we have created a bank, for 'deposits &amp; withdrawals' of all the bits &amp; bytes that one will ever need to build any noble dream (however limitless). We will vault all this knowledge in our bank, in the form of unadulterated excerpts from the brains, lives, experiences of 'reputable great minds', specific to every niche, field, industry, expertise etc. By means of your incessant contributions, we will surpass Google (attain limitlessness), reshaping the worldwide web with the freshness of our awesomeness.&nbsp;</p>
<p>@surpassinggoogle&nbsp;</p>
<h2>image for row 8:</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52878599-fdd61800-3197-11e9-8e5e-7b2b621c46a3.png" width="1366" height="444"/></p>
<p><br></p>
<p>We don't have the resource materials for this row ready yet. For now, you can simply embed this video 'https://youtu.be/N0WleFfFUtU' and for the corresponding text on the other side, simply add this; <em>"STEEMGIGS na helele"</em>. <a href="https://ulogs.org/@princessvanessa">@princessvanessa</a></p>
<h2>image for row 9:</h2>
<h2><img src="https://user-images.githubusercontent.com/23729959/52879966-a639ab80-319b-11e9-881d-cdd1475ea497.png" width="1366" height="346"/>&nbsp;</h2>
<blockquote>The explore button on this row will alert users with the text<strong> 'This feature is coming soon'.</strong></blockquote>
<h2>image for row 10:</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52880508-1dbc0a80-319d-11e9-8f04-38055d81d697.png" width="1366" height="402"/></p>
<blockquote>These thumbnails will eventually lead to a variety of articles but since these articles aren't ready yet, simply let each lead to or pull from this URL; 'https://ulogs.org/@surpassinggoogle/the-grand-picture-the-detailed-faq-s-for-https-steemgigs-org-and-all-the-answers-please-bookmark-this'</blockquote>
<h2>image for row 11:&nbsp;</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52895243-7ff32a80-31f2-11e9-9d26-bc4789cb9b38.png" width="1366" height="268"/></p>
<blockquote>The 'Get Started' should alert user to sign-in or sign up.</blockquote>
<h2>image for row 12:</h2>
<p><img src="https://user-images.githubusercontent.com/23729959/52895416-0f99d880-31f5-11e9-8a69-4232b8d00fb5.png" width="1366" height="526"/></p>
<p><br></p>
<p>For this row, we don't have yet, all the respective URL, so i will enlist the few that we have available.</p>
<ul>
  <li>Discord Talks - https://discord.gg/wWrnSXK</li>
  <li>Help - https://discord.gg/wWrnSXK</li>
  <li>FAQ - https://ulogs.org/@surpassinggoogle/the-grand-picture-the-detailed-faq-s-for-https-steemgigs-org-and-all-the-answers-please-bookmark-this</li>
  <li>Updates - https://ulogs.org/@steemgigs</li>
  <li>Twitter Icon - https://twitter.com/@steemgigs</li>
  <li>Facebook Icon - https://www.facebook.com/profile.php?id=1418278338268953</li>
  <li>Steem Icon - https://ulogs.org/@steemgigs</li>
</ul>
<p><br></p>
<h1>Component</h1>
<ul>
  <li><a href="https://github.com/steemgigs/steemgigs">Steemgigs (Front-End)</a>&nbsp;</li>
  <li><a href="https://github.com/steemgigs/steemgigsServer">SteemgigsServer (Back-End)</a></li>
</ul>
<p>Taking a look at our current landing page is a good starting point. Also across the entire task, it is essential to test your code on different browsers and mobile to make sure the end-product renders well on each.</p>
<p>Where you get stuck, we can always discuss possible solutions, logic etc We just may find answers!</p>
<blockquote>Overall, carry out the task according to your preference and expertise with UX in mind, submitting a pull request and thereafter creating a post highlighting your contribution, following Utopian's guidelines for Development (contributions) as such posts are likely to be curated by utopian.io</blockquote>
<h1>Deadline</h1>
<p>3 days&nbsp;&nbsp;&nbsp;</p>
<h1>Communication</h1>
<p>You can contact me on:&nbsp; &nbsp; &nbsp; &nbsp;</p>
<ul>
  <li><a href="https://t.me/teardrops_smt"><strong>Telegram </strong></a><strong>(username: </strong><a href="https://steemit.com/@surpassinggoogle"><strong>@surpassinggoogle</strong></a><strong>)</strong></li>
  <li><a href="https://discord.gg/7bUFymy"><strong>Discord</strong></a><strong> (username: surpassinggoogle#1660)</strong></li>
</ul>
<blockquote>You can also indicate interest by leaving a comment underneath this post or on Github.&nbsp;</blockquote>
<blockquote>It is recommended that we are able to&nbsp;discuss, for a better understanding of the task.</blockquote>
<h1><strong>Github</strong></h1>
<ul>
  <li><a href="https://github.com/steemgigs/steemgigs">Steemgigs (Front-End)</a>&nbsp;</li>
  <li><a href="https://github.com/steemgigs/steemgigsServer">SteemgigsServer (Back-End)</a></li>
</ul>
<p><br></p>
<p>Kindly support us by voting on the 'steemgigs' witness.</p>
</html>
Find clearer images on:
https://ulogs.org/steemgigs/@surpassinggoogle/task-request-help-us-design-re-design-the-steemgigs-org-landing-page-additional-bounty-of-50-steem

**Comment by tobias-g1** [comment]
Resolved in #104
